apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: gcr.io/blog-261010/wurstmeister/kafka:2.12-2.5.0
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: localhost
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name : KAFKA_CREATE_TOPICS
              value: testTopic:1:1
          ports:
            - containerPort: 9092
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 60

